-- Datos iniciales de invitados con códigos de invitación únicos
INSERT INTO guests (name, invite_code, max_companions) VALUES
  ('Miguel',         'UBWEL5DZD4', 1),
  ('Kike',           'DMYE5RRW59', 1),
  ('Elkin',          'KT6AJF4GNP', 1),
  ('Sr. David',      'U4432WDK93', 1),
  ('Juan',           'JZ4C6VXG7S', 0),
  ('Abuela',         'LTYWHUN9S9', 0),
  ('José Matías',    'NNUCVXB9ZC', 2),
  ('José Luis',      'YH6ZBP95KA', 0),
  ('Anthony',        'CT2KWYUKHW', 0),
  ('Sra. Elizabeth', 'AYEYJV5PV2', 1),
  ('Keyla',          'V9DPY3YA9G', 2),
  ('Jhoany',         'SLL6YGWB68', 0),
  ('Estewill',       'AFDKDU25S2', 1),
  ('Stiven',         '6424W4UTGW', 1),
  ('Carlos',         'W9S6HRXGZD', 1),
  ('Cristian',       '9G6GYWBJA7', 1),
  ('Edwin',          'YW9MXUFR4G', 1),
  ('Pechy',          '5Y5DCJAFHT', 1),
  ('William',        '9728T9VNSJ', 0),
  ('Samir',          '2VLE4FFEKA', 0),
  ('Tía Esther',     'VKCZEBFHQ3', 1),
  ('Armandito',      'RC383XM6L9', 1),
  ('Jandy',          'NETSPWBQ2Q', 1),
  ('Johan',          'SXLBNRHQFD', 1),
  ('Abuelita Aba',   'FQEVYBL9D5', 0),
  ('Melissa',        'G28Y7WPAMK', 0)
ON CONFLICT (invite_code) DO NOTHING;
